POST http://localhost:3000/campaigns

{
    "name": "Teste campaign 2",
    "content": "New account 2",
    "emails": ["test2@mail.com"]
}

###

GET http://localhost:3000/campaigns

###

GET http://localhost:3000/campaigns/:ID