POST http://localhost:3000/campaigns

{
    "name": "Teste campaign",
    "content": "Test content",
    "emails": ["test@mail.com"]
}

###

GET http://localhost:3000/campaigns

###

GET http://localhost:3000/campaigns/:ID

###

PATCH http://localhost:3000/campaigns/cancel/:ID

###

DELETE http://localhost:3000/campaigns/:ID