@url = http://localhost:3000
@identity_provider = http://localhost:8080
@username = USER_EMAIL
@password = USER_PASSWORD
@access_token = {{token.response.body.access_token}}

###

GET {{url}}/ping

###

POST {{url}}/campaigns
Authorization: Bearer {{access_token}}

{
    "name": "Teste campaign",
    "content": "Test content",
    "emails": ["test@mail.com"]
}

###

GET {{url}}/campaigns
Authorization: Bearer {{access_token}}

###

GET {{url}}/campaigns/:ID
Authorization: Bearer {{access_token}}

###

DELETE {{url}}/campaigns/:ID
Authorization: Bearer {{access_token}}

###
# @name token
POST {{identity_provider}}/realms/emailn_provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&username={{username}}&password={{password}}&grant_type=password